name: ESLint

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v1
    - name: Use Node
      uses: actions/setup-node@v1
    - name: npm install
      run: npm i
    - name: npm run lint
      run: npm run lint
